package auto.cn.greendaogenerate;

import auto.cn.greendaogenerate.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CONTENT_LIST".
 */
public class ContentList {

    private Long id;
    private String CONTENT_ID;
    private String CONTENT_PL_BZ_ID;
    private String CONTENT_PART_ID;
    private String CONTENT_ITEM_ID;
    private String CONTENT_NAME;
    private String CONTENT_CONTENT_TYPE;
    private Integer CONTENT_SORT;
    private String CONTENT_WAY;
    private Integer CONTENT_IS_USE;
    private String CONTENT_STANDARD;
    private Integer CONTENT_IS_PHOTO;
    private Integer CONTENT_IS_PHOTO_EXCEPTION;
    private String CONTENT_CREATE_DATE;
    private String CONTENT_ALARM_H1;
    private String CONTENT_ALARM_H2;
    private String CONTENT_ALARM_STYLE;
    private String Valid_Flag;
    private String CODE_NAME;
    private String temp_value;
    private String photo_path;
    private Boolean content_finish;
    private Long fk_item;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient ContentListDao myDao;

    private ItemList itemList;
    private Long itemList__resolvedKey;


    public ContentList() {
    }

    public ContentList(Long id) {
        this.id = id;
    }

    public ContentList(Long id, String CONTENT_ID, String CONTENT_PL_BZ_ID, String CONTENT_PART_ID, String CONTENT_ITEM_ID, String CONTENT_NAME, String CONTENT_CONTENT_TYPE, Integer CONTENT_SORT, String CONTENT_WAY, Integer CONTENT_IS_USE, String CONTENT_STANDARD, Integer CONTENT_IS_PHOTO, Integer CONTENT_IS_PHOTO_EXCEPTION, String CONTENT_CREATE_DATE, String CONTENT_ALARM_H1, String CONTENT_ALARM_H2, String CONTENT_ALARM_STYLE, String Valid_Flag, String CODE_NAME, String temp_value, String photo_path, Boolean content_finish, Long fk_item) {
        this.id = id;
        this.CONTENT_ID = CONTENT_ID;
        this.CONTENT_PL_BZ_ID = CONTENT_PL_BZ_ID;
        this.CONTENT_PART_ID = CONTENT_PART_ID;
        this.CONTENT_ITEM_ID = CONTENT_ITEM_ID;
        this.CONTENT_NAME = CONTENT_NAME;
        this.CONTENT_CONTENT_TYPE = CONTENT_CONTENT_TYPE;
        this.CONTENT_SORT = CONTENT_SORT;
        this.CONTENT_WAY = CONTENT_WAY;
        this.CONTENT_IS_USE = CONTENT_IS_USE;
        this.CONTENT_STANDARD = CONTENT_STANDARD;
        this.CONTENT_IS_PHOTO = CONTENT_IS_PHOTO;
        this.CONTENT_IS_PHOTO_EXCEPTION = CONTENT_IS_PHOTO_EXCEPTION;
        this.CONTENT_CREATE_DATE = CONTENT_CREATE_DATE;
        this.CONTENT_ALARM_H1 = CONTENT_ALARM_H1;
        this.CONTENT_ALARM_H2 = CONTENT_ALARM_H2;
        this.CONTENT_ALARM_STYLE = CONTENT_ALARM_STYLE;
        this.Valid_Flag = Valid_Flag;
        this.CODE_NAME = CODE_NAME;
        this.temp_value = temp_value;
        this.photo_path = photo_path;
        this.content_finish = content_finish;
        this.fk_item = fk_item;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getContentListDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCONTENT_ID() {
        return CONTENT_ID;
    }

    public void setCONTENT_ID(String CONTENT_ID) {
        this.CONTENT_ID = CONTENT_ID;
    }

    public String getCONTENT_PL_BZ_ID() {
        return CONTENT_PL_BZ_ID;
    }

    public void setCONTENT_PL_BZ_ID(String CONTENT_PL_BZ_ID) {
        this.CONTENT_PL_BZ_ID = CONTENT_PL_BZ_ID;
    }

    public String getCONTENT_PART_ID() {
        return CONTENT_PART_ID;
    }

    public void setCONTENT_PART_ID(String CONTENT_PART_ID) {
        this.CONTENT_PART_ID = CONTENT_PART_ID;
    }

    public String getCONTENT_ITEM_ID() {
        return CONTENT_ITEM_ID;
    }

    public void setCONTENT_ITEM_ID(String CONTENT_ITEM_ID) {
        this.CONTENT_ITEM_ID = CONTENT_ITEM_ID;
    }

    public String getCONTENT_NAME() {
        return CONTENT_NAME;
    }

    public void setCONTENT_NAME(String CONTENT_NAME) {
        this.CONTENT_NAME = CONTENT_NAME;
    }

    public String getCONTENT_CONTENT_TYPE() {
        return CONTENT_CONTENT_TYPE;
    }

    public void setCONTENT_CONTENT_TYPE(String CONTENT_CONTENT_TYPE) {
        this.CONTENT_CONTENT_TYPE = CONTENT_CONTENT_TYPE;
    }

    public Integer getCONTENT_SORT() {
        return CONTENT_SORT;
    }

    public void setCONTENT_SORT(Integer CONTENT_SORT) {
        this.CONTENT_SORT = CONTENT_SORT;
    }

    public String getCONTENT_WAY() {
        return CONTENT_WAY;
    }

    public void setCONTENT_WAY(String CONTENT_WAY) {
        this.CONTENT_WAY = CONTENT_WAY;
    }

    public Integer getCONTENT_IS_USE() {
        return CONTENT_IS_USE;
    }

    public void setCONTENT_IS_USE(Integer CONTENT_IS_USE) {
        this.CONTENT_IS_USE = CONTENT_IS_USE;
    }

    public String getCONTENT_STANDARD() {
        return CONTENT_STANDARD;
    }

    public void setCONTENT_STANDARD(String CONTENT_STANDARD) {
        this.CONTENT_STANDARD = CONTENT_STANDARD;
    }

    public Integer getCONTENT_IS_PHOTO() {
        return CONTENT_IS_PHOTO;
    }

    public void setCONTENT_IS_PHOTO(Integer CONTENT_IS_PHOTO) {
        this.CONTENT_IS_PHOTO = CONTENT_IS_PHOTO;
    }

    public Integer getCONTENT_IS_PHOTO_EXCEPTION() {
        return CONTENT_IS_PHOTO_EXCEPTION;
    }

    public void setCONTENT_IS_PHOTO_EXCEPTION(Integer CONTENT_IS_PHOTO_EXCEPTION) {
        this.CONTENT_IS_PHOTO_EXCEPTION = CONTENT_IS_PHOTO_EXCEPTION;
    }

    public String getCONTENT_CREATE_DATE() {
        return CONTENT_CREATE_DATE;
    }

    public void setCONTENT_CREATE_DATE(String CONTENT_CREATE_DATE) {
        this.CONTENT_CREATE_DATE = CONTENT_CREATE_DATE;
    }

    public String getCONTENT_ALARM_H1() {
        return CONTENT_ALARM_H1;
    }

    public void setCONTENT_ALARM_H1(String CONTENT_ALARM_H1) {
        this.CONTENT_ALARM_H1 = CONTENT_ALARM_H1;
    }

    public String getCONTENT_ALARM_H2() {
        return CONTENT_ALARM_H2;
    }

    public void setCONTENT_ALARM_H2(String CONTENT_ALARM_H2) {
        this.CONTENT_ALARM_H2 = CONTENT_ALARM_H2;
    }

    public String getCONTENT_ALARM_STYLE() {
        return CONTENT_ALARM_STYLE;
    }

    public void setCONTENT_ALARM_STYLE(String CONTENT_ALARM_STYLE) {
        this.CONTENT_ALARM_STYLE = CONTENT_ALARM_STYLE;
    }

    public String getValid_Flag() {
        return Valid_Flag;
    }

    public void setValid_Flag(String Valid_Flag) {
        this.Valid_Flag = Valid_Flag;
    }

    public String getCODE_NAME() {
        return CODE_NAME;
    }

    public void setCODE_NAME(String CODE_NAME) {
        this.CODE_NAME = CODE_NAME;
    }

    public String getTemp_value() {
        return temp_value;
    }

    public void setTemp_value(String temp_value) {
        this.temp_value = temp_value;
    }

    public String getPhoto_path() {
        return photo_path;
    }

    public void setPhoto_path(String photo_path) {
        this.photo_path = photo_path;
    }

    public Boolean getContent_finish() {
        return content_finish;
    }

    public void setContent_finish(Boolean content_finish) {
        this.content_finish = content_finish;
    }

    public Long getFk_item() {
        return fk_item;
    }

    public void setFk_item(Long fk_item) {
        this.fk_item = fk_item;
    }

    /** To-one relationship, resolved on first access. */
    public ItemList getItemList() {
        Long __key = this.fk_item;
        if (itemList__resolvedKey == null || !itemList__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ItemListDao targetDao = daoSession.getItemListDao();
            ItemList itemListNew = targetDao.load(__key);
            synchronized (this) {
                itemList = itemListNew;
            	itemList__resolvedKey = __key;
            }
        }
        return itemList;
    }

    public void setItemList(ItemList itemList) {
        synchronized (this) {
            this.itemList = itemList;
            fk_item = itemList == null ? null : itemList.getId();
            itemList__resolvedKey = fk_item;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
