package auto.cn.greendaogenerate;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import auto.cn.greendaogenerate.PlanList;
import auto.cn.greendaogenerate.AreaList;
import auto.cn.greendaogenerate.Equiplist;
import auto.cn.greendaogenerate.PartList;
import auto.cn.greendaogenerate.ItemList;
import auto.cn.greendaogenerate.ContentList;

import auto.cn.greendaogenerate.PlanListDao;
import auto.cn.greendaogenerate.AreaListDao;
import auto.cn.greendaogenerate.EquiplistDao;
import auto.cn.greendaogenerate.PartListDao;
import auto.cn.greendaogenerate.ItemListDao;
import auto.cn.greendaogenerate.ContentListDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig planListDaoConfig;
    private final DaoConfig areaListDaoConfig;
    private final DaoConfig equiplistDaoConfig;
    private final DaoConfig partListDaoConfig;
    private final DaoConfig itemListDaoConfig;
    private final DaoConfig contentListDaoConfig;

    private final PlanListDao planListDao;
    private final AreaListDao areaListDao;
    private final EquiplistDao equiplistDao;
    private final PartListDao partListDao;
    private final ItemListDao itemListDao;
    private final ContentListDao contentListDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        planListDaoConfig = daoConfigMap.get(PlanListDao.class).clone();
        planListDaoConfig.initIdentityScope(type);

        areaListDaoConfig = daoConfigMap.get(AreaListDao.class).clone();
        areaListDaoConfig.initIdentityScope(type);

        equiplistDaoConfig = daoConfigMap.get(EquiplistDao.class).clone();
        equiplistDaoConfig.initIdentityScope(type);

        partListDaoConfig = daoConfigMap.get(PartListDao.class).clone();
        partListDaoConfig.initIdentityScope(type);

        itemListDaoConfig = daoConfigMap.get(ItemListDao.class).clone();
        itemListDaoConfig.initIdentityScope(type);

        contentListDaoConfig = daoConfigMap.get(ContentListDao.class).clone();
        contentListDaoConfig.initIdentityScope(type);

        planListDao = new PlanListDao(planListDaoConfig, this);
        areaListDao = new AreaListDao(areaListDaoConfig, this);
        equiplistDao = new EquiplistDao(equiplistDaoConfig, this);
        partListDao = new PartListDao(partListDaoConfig, this);
        itemListDao = new ItemListDao(itemListDaoConfig, this);
        contentListDao = new ContentListDao(contentListDaoConfig, this);

        registerDao(PlanList.class, planListDao);
        registerDao(AreaList.class, areaListDao);
        registerDao(Equiplist.class, equiplistDao);
        registerDao(PartList.class, partListDao);
        registerDao(ItemList.class, itemListDao);
        registerDao(ContentList.class, contentListDao);
    }
    
    public void clear() {
        planListDaoConfig.getIdentityScope().clear();
        areaListDaoConfig.getIdentityScope().clear();
        equiplistDaoConfig.getIdentityScope().clear();
        partListDaoConfig.getIdentityScope().clear();
        itemListDaoConfig.getIdentityScope().clear();
        contentListDaoConfig.getIdentityScope().clear();
    }

    public PlanListDao getPlanListDao() {
        return planListDao;
    }

    public AreaListDao getAreaListDao() {
        return areaListDao;
    }

    public EquiplistDao getEquiplistDao() {
        return equiplistDao;
    }

    public PartListDao getPartListDao() {
        return partListDao;
    }

    public ItemListDao getItemListDao() {
        return itemListDao;
    }

    public ContentListDao getContentListDao() {
        return contentListDao;
    }

}
