package auto.cn.greendaogenerate;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import auto.cn.greendaogenerate.PartList;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PART_LIST".
*/
public class PartListDao extends AbstractDao<PartList, Long> {

    public static final String TABLENAME = "PART_LIST";

    /**
     * Properties of entity PartList.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PART_ID = new Property(1, String.class, "PART_ID", false, "PART__ID");
        public final static Property PART_BZ_ID = new Property(2, String.class, "PART_BZ_ID", false, "PART__BZ__ID");
        public final static Property PART_NAME = new Property(3, String.class, "PART_NAME", false, "PART__NAME");
        public final static Property PART_CREATE_DATE = new Property(4, String.class, "PART_CREATE_DATE", false, "PART__CREATE__DATE");
        public final static Property Valid_Flag = new Property(5, String.class, "Valid_Flag", false, "VALID__FLAG");
        public final static Property PART_FINISH = new Property(6, Boolean.class, "PART_FINISH", false, "PART__FINISH");
        public final static Property Fk_equip = new Property(7, Long.class, "fk_equip", false, "FK_EQUIP");
    };

    private DaoSession daoSession;

    private Query<PartList> equiplist_PartsQuery;

    public PartListDao(DaoConfig config) {
        super(config);
    }
    
    public PartListDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PART_LIST\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"PART__ID\" TEXT," + // 1: PART_ID
                "\"PART__BZ__ID\" TEXT," + // 2: PART_BZ_ID
                "\"PART__NAME\" TEXT," + // 3: PART_NAME
                "\"PART__CREATE__DATE\" TEXT," + // 4: PART_CREATE_DATE
                "\"VALID__FLAG\" TEXT," + // 5: Valid_Flag
                "\"PART__FINISH\" INTEGER," + // 6: PART_FINISH
                "\"FK_EQUIP\" INTEGER);"); // 7: fk_equip
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PART_LIST\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, PartList entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String PART_ID = entity.getPART_ID();
        if (PART_ID != null) {
            stmt.bindString(2, PART_ID);
        }
 
        String PART_BZ_ID = entity.getPART_BZ_ID();
        if (PART_BZ_ID != null) {
            stmt.bindString(3, PART_BZ_ID);
        }
 
        String PART_NAME = entity.getPART_NAME();
        if (PART_NAME != null) {
            stmt.bindString(4, PART_NAME);
        }
 
        String PART_CREATE_DATE = entity.getPART_CREATE_DATE();
        if (PART_CREATE_DATE != null) {
            stmt.bindString(5, PART_CREATE_DATE);
        }
 
        String Valid_Flag = entity.getValid_Flag();
        if (Valid_Flag != null) {
            stmt.bindString(6, Valid_Flag);
        }
 
        Boolean PART_FINISH = entity.getPART_FINISH();
        if (PART_FINISH != null) {
            stmt.bindLong(7, PART_FINISH ? 1L: 0L);
        }
 
        Long fk_equip = entity.getFk_equip();
        if (fk_equip != null) {
            stmt.bindLong(8, fk_equip);
        }
    }

    @Override
    protected void attachEntity(PartList entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public PartList readEntity(Cursor cursor, int offset) {
        PartList entity = new PartList( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // PART_ID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // PART_BZ_ID
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // PART_NAME
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // PART_CREATE_DATE
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // Valid_Flag
            cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0, // PART_FINISH
            cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7) // fk_equip
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, PartList entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPART_ID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPART_BZ_ID(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPART_NAME(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPART_CREATE_DATE(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setValid_Flag(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setPART_FINISH(cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0);
        entity.setFk_equip(cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(PartList entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(PartList entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "parts" to-many relationship of Equiplist. */
    public List<PartList> _queryEquiplist_Parts(Long fk_equip) {
        synchronized (this) {
            if (equiplist_PartsQuery == null) {
                QueryBuilder<PartList> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Fk_equip.eq(null));
                equiplist_PartsQuery = queryBuilder.build();
            }
        }
        Query<PartList> query = equiplist_PartsQuery.forCurrentThread();
        query.setParameter(0, fk_equip);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getEquiplistDao().getAllColumns());
            builder.append(" FROM PART_LIST T");
            builder.append(" LEFT JOIN EQUIPLIST T0 ON T.\"FK_EQUIP\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected PartList loadCurrentDeep(Cursor cursor, boolean lock) {
        PartList entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Equiplist equiplist = loadCurrentOther(daoSession.getEquiplistDao(), cursor, offset);
        entity.setEquiplist(equiplist);

        return entity;    
    }

    public PartList loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<PartList> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<PartList> list = new ArrayList<PartList>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<PartList> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<PartList> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
